// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFc9YhY7hrNCXF-itB1wOaJKR2IFki50s',
    appId: '1:480289567495:web:7ab936b426159b76a54ba2',
    messagingSenderId: '480289567495',
    projectId: 'limmat-boeoettle-guide',
    authDomain: 'limmat-boeoettle-guide.firebaseapp.com',
    storageBucket: 'limmat-boeoettle-guide.appspot.com',
    measurementId: 'G-1MWDDHRZHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeXgF0L5H-gGWIuNx43KcokgqCk9x4cw',
    appId: '1:480289567495:android:02ca8b2423eb937aa54ba2',
    messagingSenderId: '480289567495',
    projectId: 'limmat-boeoettle-guide',
    storageBucket: 'limmat-boeoettle-guide.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtPmp2jZscA2bBY4puzgHCi6Ht2nXeno',
    appId: '1:480289567495:ios:101e07bbd4c436a5a54ba2',
    messagingSenderId: '480289567495',
    projectId: 'limmat-boeoettle-guide',
    storageBucket: 'limmat-boeoettle-guide.appspot.com',
    iosBundleId: 'ch.limmat.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtPmp2jZscA2bBY4puzgHCi6Ht2nXeno',
    appId: '1:480289567495:ios:101e07bbd4c436a5a54ba2',
    messagingSenderId: '480289567495',
    projectId: 'limmat-boeoettle-guide',
    storageBucket: 'limmat-boeoettle-guide.appspot.com',
    iosBundleId: 'ch.limmat.app',
  );

}